// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:pills_reminder/features/medications/data/models/hive/medication_model_adapter.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(MedicationModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(MedicationModelAdapter());
  }
}
